<?php

function drush_drake_settings(){
  $form['drush_drake_scripts_dir' ] = array(
    '#title' => t('Drake Scripts Dir'),
    '#description' => t('The filepath for drake scripts. No trailing / please.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('drush_drake_scripts_dir', "scripts/drush_drake"),
  );

  $form['disable_community'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show Export Drake Button'),
    '#description' => t('Show the Export to Drake button on system settings forms.'),
    '#default_value' => variable_get('drush_drake_show_export', TRUE),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_menu()
 */
function drush_drake_menu() {
  $items['admin/settings/drush_drake'] = array(
    'title' => 'Drush Drake Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drush_drake_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/*
 * Alter any of the system_settings_form instances to allow for
 * export to a drake script. 
 */
function drush_drake_form_alter(&$form, &$form_state, $form_id) {
  if (is_array($form['#submit']) && in_array('system_settings_form_submit', $form['#submit'])) {
    $form['buttons']['drake_export'] = array('#type' => 'submit', '#value' => t('Save and export to drake file') );
    $form['#submit'][] = "_drush_drake_export_system_settings_form";
  }
}

/*
 * Submit handler for system_settings_form drake script export.
 * Write each form value to a drake script line:
 * vset var_name var_value.
 * 
 */
function _drush_drake_export_system_settings_form($form, &$form_state) {
  $export_file = $form_state['clicked_button']['#value'] == "Save and export to drake file";
  
  if ($export_file) {
    // Exclude unnecessary elements.
    unset($form_state['values']['submit'], $form_state['values']['reset'], $form_state['values']['drake_export'], $form_state['values']['form_id'], $form_state['values']['op'], $form_state['values']['form_token'], $form_state['values']['form_build_id']);
    
    $vars = $form_state['values'] ;

    foreach ($form_state['values'] as $key => $value) {
      $vars[$key] = sprintf("vset %s %s", $key, serialize($value));
    }

    $script_to_write = implode("\n", $vars);
    module_load_include('inc', 'drush_drake', 'drake.drush');
    $filename = drush_drake_file(false);

    $fh = fopen($filename, "w");
    fwrite($fh, $script_to_write);
    fclose($fh);
    drupal_set_message(t('Exported form settings to @filepath', array('@filepath' => $filename)));
  }
}